version: '3.3'
services:
  app:
    image: ${PROJ_NAME}:latest
    container_name: ${PROJ_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/node/app
      # - app-volume:/home/node/app/node_modules
    ports:
      - ${DEV_PORT}:3000
    tty: true
volumes:
  app-volume:
    name: ${PROJ_NAME}-volume
    driver: local
